routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes(['verify' => true]);

Route::get('/','Efiwura\PagesController@index')->name('index');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/properties','Efiwura\PagesController@showPropertiesPage')->name('properties');

Route::get('/about',  'Efiwura\PagesController@about')->name('about');

Route::get('/faq',  'Efiwura\PagesController@faq')->name('faq');

Route::get('contact', 'Efiwura\PagesController@showContactPage')->name('contact');

Route::get('/properties/{slug}','Efiwura\PagesController@showPropertyDetailsPage')->name('details');

Route::get('/advertise','Efiwura\PagesController@showAdvertisePage')->name('advertise')->middleware('verified');

Route::resource('property', 'Efiwura\PropertiesController')->middleware('verified');

resources/views/pages/about.blade.php
@extends('layouts.app')

@section('title')
About
@endsection

@section('content')
{{-- About start --}}
<section class="at-agents-sec">
    <div class="container" style=" margin-top:-80px;">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="at-sec-title">
                    <h3>About Efiwura</span></h3>

                    <div class="at-heading-under-line">
                        <div class="at-heading-inside-line"></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row animatedParent animateOnce">
            {{-- About efiwura start --}}
            <div class="col-xl-7 col-lg-6 col-md-12">
                <div class="at-about-col at-col-default-mar">

                    <div class="at-about-title">
                        <h4>Few description about Efiwura</h4>
                        <h6>Real Estate</h6>
                    </div>

                    <p>
                        There are many variations of passages of Lorem Ipsum available,
                        but the majority have suffered alteration in some form, by injected humour,
                        or randomised words which dont look even slightly believable.
                        If you are going to a passage of Lorem Ipsum.
                    </p>

                    <p>
                        There are many variations of passages of Lorem Ipsum available,
                        but the majority have suffered alteration in some form, by injected humour,
                        or randomised words which dont look even slightly believable.
                        If you are going to a passage of Lorem Ipsum.
                    </p>

                </div>
            </div>
            {{-- About efiwura end --}}
            {{-- About Image start --}}
            <div class="col-xl-5 col-lg-6 col-md-6">
                <div class="at-about-col animated fadeInRightShort slow delay-250">
                    <img class="img img-thumbnail" src="images/about/2.jpg" alt="image" style="height:300px">
                </div>
            </div>
            {{-- About image end --}}
        </div>
        <hr>
        {{-- Mission vission starts here --}}
        <div class="row">

            <div class="col-md-4 mb-2">
                <div class="card card-default">
                    <div class="at-sec-title at-sec-title-left">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fa fa-balance-scale"></i>
                                OUR MISSION
                            </h3>
                        </div>
                        <div class="card-body">
                            <p> There are many variations of passages of Lorem Ipsum available,
                                but the majority have suffered alteration in some form, by injected humour,
                                or randomised words which dont look even slightly believable.
                                If you are going to a passage of Lorem Ipsum.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-2">
                <div class="card card-default">
                    <div class="at-sec-title at-sec-title-left">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fa fa-eye fa-fw"></i>
                                OUR VISION
                            </h3>
                        </div>
                        <div class="card-body">
                            <p>
                                There are many variations of passages of Lorem Ipsum available,
                                but the majority have suffered alteration in some form, by injected humour,
                                or randomised words which dont look even slightly believable.
                                If you are going to a passage of Lorem Ipsum.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-2">
                <div class="card card-default">
                    <div class="at-sec-title at-sec-title-left">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fa fa-diamond"></i>
                                OUR VALUES
                            </h3>
                        </div>
                        <div class="card-body">
                            <p>There are many variations of passages of Lorem Ipsum available,
                                but the majority have suffered alteration in some form, by injected humour,
                                or randomised words which dont look even slightly believable.
                                If you are going to a passage of Lorem Ipsum.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        {{-- Mission vission ends here --}}
    </div>

</section>

<!-- About End -->

@endsection

resources/views/pages/advertise.blade.php
@extends('layouts.app')

@section('title')
Advertise
@endsection
@section('css')
<link rel="stylesheet" href="{{ asset('css/dropzone.min.css') }}">
@endsection
@section('content')


<section class="at-agents-sec"
    style="background-image: url('https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')">
    <div class="container" style=" margin-top:-80px;">

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="shadow p-4 bg-white" style="border-radius: 20px;">
                    {{-- Property tab start --}}
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="text-warning nav-item nav-link active" id="nav-home-tab" data-toggle="tab"
                                href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Ad Info</a>
                            <a class="text-warning nav-item nav-link" id="nav-profile-tab" data-toggle="tab"
                                href="#nav-profile" role="tab" aria-controls="nav-profile"
                                aria-selected="false">Location</a>
                            <a class="text-warning nav-item nav-link" id="nav-contact-tab" data-toggle="tab"
                                href="#nav-contact" role="tab" aria-controls="nav-contact"
                                aria-selected="false">Features</a>
                            <a class="text-warning nav-item nav-link" id="nav-image-tab" data-toggle="tab"
                                href="#nav-image" role=" tab" aria-controls="nav-image" aria-selected="false">Images</a>
                        </div>
                    </nav>
                    {{-- Property tab end --}}

                    {{-- Property form start --}}
                    <form action="{{ route('property.store') }}" enctype="multipart/form-data" method="POST">

                        <div class="tab-content" id="nav-tabContent">

                            <div class="tab-pane fade show active" id="nav-home" role="tabpanel"
                                aria-labelledby="nav-home-tab">
                                <div class="form-group">
                                    <label for="firstname">Title</label>
                                    <input type="text" id="title" class="form-control" name="firstname" />
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea name="description" id="description" class="form-control"
                                        placeholder="Describe your property" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="property_type">Property Type</label>
                                    <select class="form-control" name="property_type" id="property_type">
                                        <option value="">Select One</option>
                                        <option value="">Building</option>
                                        <option value="">Land</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="property_type">Category</label>
                                    <select class="form-control" name="property_type" id="property_type">
                                        <option value="">Select One</option>
                                        <option value="">For Sale</option>
                                        <option value="">For Rent</option>
                                    </select>
                                </div>

                            </div>
                            <div class="tab-pane fade" id="nav-profile" role="tabpanel"
                                aria-labelledby="nav-profile-tab">

                                <div class="form-group">
                                    <label for="">Price</label>
                                    <input type="text" id="lastname" class="form-control" name="lastname" />
                                </div>
                                <div class="form-group">
                                    <label for="property_type">Status</label>
                                    <select class="form-control" name="property_type" id="property_type">
                                        <option value="">Select One</option>
                                        <option value="">Old</option>
                                        <option value="">New</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="property_type">Region</label>
                                    <select class="form-control" name="property_type" id="property_type">
                                        <option value="">Select One</option>
                                        <option value="">Accra</option>
                                        <option value="">Sunyani</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="">Address</label>
                                    <input type="text" id="address" class="form-control" name="lastname" />
                                </div>
                            </div>
                            <div class="tab-pane fade" id="nav-contact" role="tabpanel"
                                aria-labelledby="nav-contact-tab">
                                <div class="form-group">
                                    <label for="property_type">Features</label>
                                    <select class="form-control" name="property_type" id="property_type">
                                        <option value="">Select One</option>
                                        <option value="">Old</option>
                                        <option value="">New</option>
                                    </select>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="nav-image" role="tabpanel" aria-labelledby="nav-image-tab">

                                <div class="form-group">
                                    <label for="">Upload Some images</label>
                                    <div class="dropzone" id="myID"></div>
                                </div>
                            </div>
                        </div>



                        <button type="submit" class="btn btn-success" id="submit-all"> Submit
                            Property </button>
                    </form>
                    {{-- Property form end --}}
                </div>
            </div>
        </div>
    </div>
</section>

@endsection
@section('js')
<script src="{{ asset('js/dropzone.min.js') }}"></script>
<script>
    Dropzone.autoDiscover = false;
    $(document).ready(function(){
    var myDropzone = new Dropzone("div#myID",{
    url:'/property',
    autoProcessQueue: false,
    uploadMultiple: true,
    parallelUploads: 15,
    maxFiles: 15,
    maxFilesize: 5,
    acceptedFiles: 'image/*',
    addRemoveLinks: true,
    init: function() {
        dzClosure = this; 

        document.getElementById("submit-all").addEventListener("click", function(e) {
            e.preventDefault();
            e.stopPropagation();
            dzClosure.processQueue();
        });

        this.on("sendingmultiple", function(data, xhr, formData) {
            formData.append("title", jQuery("#title").val());
            formData.append("description", jQuery("#description").val());
            formData.append("_token",'{{ csrf_token() }}')
        });
        this.on('success',function(response){
            alert('success')
        })
      
    }
});
  })
</script>
<script>
    function activateSearch(){
        var input = document.getElementById('address');
        var autocomplete = new google.maps.places.Autocomplete(input);
    }
</script>
<script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCO-OqN7BviYppgz6rrxZLIa7gOElhuYb8&libraries=places&callback=activateSearch">
</script>
@endsection

resources/views/pages/contact.blade.php
@extends('layouts.app')

@section('title')
Contact Us
@endsection

@section('content')
<!-- Contact Start from here -->
<section class="at-contact-sec">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="at-contact-form at-col-default-mar">
                    <div id="form-messages"></div>
                    <form id="ajax-contact" method="post" action="php/contact.php">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                        <input type="number" class="form-control" id="number" name="number" placeholder="Phone"
                            required>
                        <textarea class="form-control" id="message" name="message" rows="5" placeholder="Message"
                            required></textarea>
                        <button class="btn btn-default hvr-bounce-to-right" type="submit">Message</button>
                    </form>
                </div>
            </div>
            <div class="col-md-6">
                <div class="at-info-box at-col-default-mar">
                    <i class="fa fa-envelope-o" aria-hidden="true"></i> <span>efiewura@gmail.com</span>
                </div>
                <div class="at-info-box at-col-default-mar">
                    <i class="fa fa-phone" aria-hidden="true"></i> <span> +233-567890</span>
                </div>
                <div class="at-info-box at-col-default-mar">
                    <i class="fa fa-map-marker" aria-hidden="true"></i> <span>Tranta Hills-Coral Avenue,Accra</span>
                </div>
            </div>
        </div>
    </div>
</section>
<!--  Contact end-->

<div id="googleMap" style="width:100%; height:400px;"></div>


@endsection

resources/views/pages/faq.blade.php
@extends('layouts.app')

@section('title')
Welcome
@endsection

@section('content')


<!-- Faq start from here -->
<section class="at-faq-sec" style="margin-top:-100px;">

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-12">

                <div style="text-align: center; margin-bottom:5%; margin-top:5%;">
                    <h3>ANSWERS TO FREQUENTLY ASKED QUESTION</h3>
                </div>

                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h2 class="mb-0">
                                <button type="button" class="btn btn-link" data-toggle="collapse"
                                    data-target="#collapseOne"><i class="fa fa-plus"></i> What is Efiwura?</button>
                            </h2>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                            data-parent="#accordionExample">
                            <div class="card-body">
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                    Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                    unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    It has survived not only five centuries, but also the leap into electronic
                                    typesetting, remaining essentially unchanged. It was popularised in the 1960s with
                                    the release of Letraset sheets containing Lorem Ipsum passages, and more recently
                                    with desktop publishing software like Aldus PageMaker including versions of Lorem
                                    Ipsum.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingTwo">
                            <h2 class="mb-0">
                                <button type="button" class="btn btn-link collapsed" data-toggle="collapse"
                                    data-target="#collapseTwo"><i class="fa fa-plus"></i> How does Efiwura
                                    works?</button>
                            </h2>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                            data-parent="#accordionExample">
                            <div class="card-body">
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                    Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                    unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    It has survived not only five centuries, but also the leap into electronic
                                    typesetting, remaining essentially unchanged. It was popularised in the 1960s with
                                    the release of Letraset sheets containing Lorem Ipsum passages, and more recently
                                    with desktop publishing software like Aldus PageMaker including versions of Lorem
                                    Ipsum.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingThree">
                            <h2 class="mb-0">
                                <button type="button" class="btn btn-link collapsed" data-toggle="collapse"
                                    data-target="#collapseThree"><i class="fa fa-plus"></i> What are the advantages of
                                    using efiwura?</button>
                            </h2>
                        </div>
                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                            data-parent="#accordionExample">
                            <div class="card-body">
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                    Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                    unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    It has survived not only five centuries, but also the leap into electronic
                                    typesetting, remaining essentially unchanged. It was popularised in the 1960s with
                                    the release of Letraset sheets containing Lorem Ipsum passages, and more recently
                                    with desktop publishing software like Aldus PageMaker including versions of Lorem
                                    Ipsum.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingFour">
                            <h2 class="mb-0">
                                <button type="button" class="btn btn-link collapsed" data-toggle="collapse"
                                    data-target="#collapseFour"><i class="fa fa-plus"></i>How do I start Advertising
                                    with Efiwura?</button>
                            </h2>
                        </div>
                        <div id="collapseFour" class="collapse" aria-labelledby="headingFour"
                            data-parent="#accordionExample">
                            <div class="card-body">
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                    Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                    unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    It has survived not only five centuries, but also the leap into electronic
                                    typesetting, remaining essentially unchanged. It was popularised in the 1960s with
                                    the release of Letraset sheets containing Lorem Ipsum passages, and more recently
                                    with desktop publishing software like Aldus PageMaker including versions of Lorem
                                    Ipsum.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingFive">
                            <h2 class="mb-0">
                                <button type="button" class="btn btn-link collapsed" data-toggle="collapse"
                                    data-target="#collapseFive"><i class="fa fa-plus"></i>How can I list my properties
                                    on Efiwura marketplace for sell?</button>
                            </h2>
                        </div>
                        <div id="collapseFive" class="collapse" aria-labelledby="headingFive"
                            data-parent="#accordionExample">
                            <div class="card-body">
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                    Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                    unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    It has survived not only five centuries, but also the leap into electronic
                                    typesetting, remaining essentially unchanged. It was popularised in the 1960s with
                                    the release of Letraset sheets containing Lorem Ipsum passages, and more recently
                                    with desktop publishing software like Aldus PageMaker including versions of Lorem
                                    Ipsum.</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</section>
<!-- Faq End -->

@endsection